### ISSUE TITLE
feat: `.preset` configuration

### ISSUE THREAD

**Issue by innocenzi** [preset/preset#56]
The idea is to implement a resolver, similar to the community resolver, which reads a `~/.preset` file to find custom repositories. 

Not sure of the format of that configuration file, but it should be able to map a `keyword:repository` to a custom Git repository.

**Comment by innocenzi** [comment]
This will most likely be done with the TOML format. 

```toml
# Simple namespace by key/value
laravel = "laravel-presets"

# Simple aliases
[app]
config = "username/config"
vitl = "username/vitl"

# Advanced table with arguments
[app.new]
preset = "username/presets"
path = "new"
ssh = false
```

But could also be YAML:

```yaml
laravel: laravel-presets
app:
  config: mgkprod/config
  vitl: mgkprod/vitl
  new:
    preset: username/presets
    path: new
    ssh: false
```

The above configurations would allow for: 

```bash
# applies laravel/tailwindcss from the laravel-presets org
npx apply laravel:tailwindcss

# applies username/config
npx apply app:config

# applies new inside username/presets
npx apply app:new
```
